Traceback (most recent call last):
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/dsmith4/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 3D plot of a spacetime diagram with x, ct, and y
url='https://glowscript.org/#/user/dasmith/folder/Public/program/SRspacetimediag'
display.IFrame(src=url1,width=600,height=500)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m [38;5;66;03m# 3D plot of a spacetime diagram with x, ct, and y[39;00m
[1;32m      2[0m url[38;5;241m=[39m[38;5;124m'[39m[38;5;124mhttps://glowscript.org/#/user/dasmith/folder/Public/program/SRspacetimediag[39m[38;5;124m'[39m
[0;32m----> 3[0m display[38;5;241m.[39mIFrame(src[38;5;241m=[39m[43murl1[49m,width[38;5;241m=[39m[38;5;241m600[39m,height[38;5;241m=[39m[38;5;241m500[39m)

[0;31mNameError[0m: name 'url1' is not defined
NameError: name 'url1' is not defined

